version: '3.7'
services:

  redis:
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
      - 8001:8001
    environment:
      - REDISEARCH_ARGS=CONCURRENT_WRITE_MODE
    volumes:
      - vector-db:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "-p", "6379", "ping"]
      interval: 2s
      timeout: 1m30s
      retries: 5
      start_period: 5s

volumes:
  vector-db:
      driver: local
      driver_opts:
        type: 'none'
        o: 'bind'
        device: 'C:\Users\jonat\Documents\DEV\MESTRADO\MsC-IPT-Big-Data\extra\CodePython\MyDocker\redis\data'

        